version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: bai10-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
